### ISSUE TITLE
Create a Welcome screen

### ISSUE THREAD

**Issue by aniishh** [aniishh/mlookup#1]
The Welcome screen for the app is only shown when the user first launches the application.
This would be a screen with the app logo/text which covers the duration in the startup of the application. (2 seconds)
The next screen would be the Login screen which would be shown after 2 seconds.

**Comment by sinoop** [comment]
![Screenshot_1586317242](https://user-images.githubusercontent.com/4647881/78742294-9645d380-7929-11ea-9424-e773e6e9cc5f.png)
